#include "main.h"

BSDATA(abilityi) = {
	{"Exploration", Positive},
	{"Brawl", Positive},
	{"Hunting", Positive},
	{"Aim", Positive},
	{"Swagger", Positive},
	{"Navigation", Positive},
	{"Reroll", Positive},
	{"Misfortune", Negative},
	{"Treasure"},
	{"Crew"},
	{"Discontent", Negative},
	{"Supply"},
	{"Hull"},
	{"Danger", Negative},
	{"DangerMaximum"},
	{"Threat", Negative},
	{"Mission", Positive},
	{"MissionMaximum", Positive},
	{"Cabine", Positive},
	{"CabineMaximum", Positive},
	{"CounterA"},
	{"CounterB"},
	{"CounterC"},
	{"CounterD"},
	{"Stars", Positive},
	{"History", Positive},
	{"Infamy", Positive},
	{"Gun1", Positive},
	{"Gun2", Positive},
	{"Gun3", Positive},
	{"Gun4", Positive},
	{"Eat", Negative},
	{"CounterX"},
};
assert_enum(abilityi, CounterX)