#include "main.h"

BSDATA(abilityi) = {
	{"Exploration"},
	{"Brawl"},
	{"Hunting"},
	{"Aim"},
	{"Swagger"},
	{"Navigation"},
	{"Reroll"},
	{"Misfortune", FG(Negative)},
	{"Crew"},
	{"Discontent", FG(Negative)},
	{"Supply"},
	{"Hull"},
	{"Danger", FG(Negative)},
	{"DangerMaximum"},
	{"Threat", FG(Negative)},
	{"Mission"},
	{"MissionMaximum"},
	{"Cabine"},
	{"CabineMaximum"},
	{"Stars"},
	{"History"},
	{"Infamy"},
	{"Gun1"},
	{"Gun2"},
	{"Gun3"},
	{"Gun4"},
};
assert_enum(abilityi, Gun4)