#include "main.h"

BSDATA(speciali) = {
	{"Name"},
	{"Nickname"},
	{"NicknameEnd"},
	{"RemoveTile"},
	{"ShowMap"},
	{"FullThrottle"},
	{"TradeFriend"},
	{"EatSupply"},
	{"ZeroCounters"},
	{"CounterName"},
	{"ChooseCounter"},
	{"ChooseCustom"},
	{"ReloadGunOrHull"},
	{"ReloadGun"},
	{"UpgradeGun"},
	{"AddGun"},
	{"AddGunUnloaded"},
	{"VisitManyTimes"},
	{"VisitRequired"},
	{"NotUseAction"},
	{"StopActions"},
	{"RemoveAllNavigation"},
	{"PlayStars"},
	{"Sail"},
	{"PageForward"},
	{"PageNext"},
	{"Entry"},
	{"MarkVisit"},
	{"SetVisit"},
	{"IfLast"},
};
assert_enum(speciali, IfLast)