#include "bsdata.h"
#include "skill.h"

BSDATA(skilli) = {
	{"Nature"},
	{"Will"},
	{"Health"},
	{"Resources"},
	{"Circles"},
	{"Administrator"},
	{"Apiarist"},
	{"Archivist"},
	{"Armorer"},
	{"Baker"},
	{"Boatcrafter"},
	{"Brewer"},
	{"Carpenter"},
	{"Cartographer"},
	{"Cook"},
	{"Deceiver"},
	{"Fighter"},
	{"Glazier"},
	{"Haggler"},
	{"Harvester"},
	{"Healer"},
	{"Hunter"},
	{"Insectrist"},
	{"Instructor"},
	{"Laborer"},
	{"Loremouse"},
	{"Militarist"},
	{"Miller"},
	{"Orator"},
	{"Pathfinder"},
	{"Persuader"},
	{"Potter"},
	{"Scientist"},
	{"Scout"},
	{"Smith"},
	{"Stonemason"},
	{"Survivalist"},
	{"WeatherWatcher"},
	{"Weaver"},
	{"Persona"},
	{"Fate"},
	{"Success"},
	{"Bonus"},
};
assert_enum(skilli, Bonus)