#include "main.h"

BSDATA(abilityi) = {
	{"Strenght"},
	{"Dexterity"},
	{"Constitution"},
	{"Intellect"},
	{"Wisdow"},
	{"Charisma"},
	{"THAC0"},
	{"Damage"},
	{"MeleeToHit"},
	{"MeleeDamage"},
	{"RangedToHit"},
	{"RangedDamage"},
	{"AC"},
	{"Level"},
	{"HP"},
	{"HPMax"},
	{"Speed"},
	{"Search"},
	{"ClimbWalls"},
	{"FindOrRemoveTraps"},
	{"HearNoise"},
	{"HideInShadows"},
	{"MoveSilently"},
	{"OpenLocks"},
	{"PickPockets"},
	{"Saves"},
	{"SaveDeath"},
	{"SaveWands"},
	{"SaveParalize"},
	{"SaveBreathWeapon"},
	{"SaveSpells"},
	{"SavePoison"},
};
assert_enum(abilityi, SavePoison)