#include "ability.h"
#include "crt.h"

BSDATA(abilityi) = {
	{"Strenght"},
	{"Dexterity"},
	{"Constitution"},
	{"Intellect"},
	{"Wisdow"},
	{"Charisma"},
	{"MeleeToHit"},
	{"MeleeDamage"},
	{"RangedToHit"},
	{"RangedDamage"},
	{"AC"},
	{"ACRanged"},
	{"Level"},
	{"HPMax"},
	{"Speed"},
	{"Search"},
	{"ClimbWalls"},
	{"FindOrRemoveTraps"},
	{"HearNoise"},
	{"HideInShadows"},
	{"MoveSilently"},
	{"OpenLocks"},
	{"PickPockets"},
	{"HideUndergrowth"},
	{"SaveDeath"},
	{"SaveWands"},
	{"SaveParalize"},
	{"SaveBreathWeapon"},
	{"SaveSpells"},
	{"SavePoison"},
	{"HP"},
	{"IllusionCopies"},
};
assert_enum(abilityi, IllusionCopies)