#include "crt.h"
#include "feat.h"

BSDATA(feati) = {
	{"EnergyDrain"},
	{"Paralysis"},
	{"PetrifyingBreath"},
	{"PetrifyingGaze"},
	{"PoisonImmunity"},
	{"CharmImmunity"},
	{"StrenghtDrain"},
	{"AcidDamage"},
	{"Blink"},
	{"ChargeDouble"},
	{"DeathGaze"},
	{"Defensive"},
	{"Stampede"},
	{"BloodSucking"},
	{"Burrowing"},
	{"Cling"},
	{"Fly"},
	{"ShapeChanging"},
	{"InflictWound"},
	{"BattleRage"},
	{"BearHug"},
	{"StunningBlow"},
	{"SurpriseEnemy"},
	{"DancePoison"},
	{"Dive"},
	{"SunSensitive"},
	{"Slow"},
	{"Quick"},
	{"Small"},
	{"Large"},
	{"Leap"},
	{"Swoop"},
	{"NormalWeaponImmunity"},
	{"Blunt"},
	{"TwoHanded"},
	{"Burned"},
	{"Frozen"},
	{"Corrosed"},
	{"Wounded"},
	{"EngageMelee"},
	{"Surprised"},
	{"Prone"},
	{"Unholy"},
	{"Summoned"},
	{"Player"},
	{"Enemy"},
};
assert_enum(feati, Enemy)