#include "bsdata.h"
#include "wear.h"

BSDATA(weari) = {
	{"Backpack"},
	{"Backpack2"},
	{"Backpack3"},
	{"Backpack4"},
	{"Backpack5"},
	{"Backpack6"},
	{"Backpack7"},
	{"Backpack8"},
	{"Backpack9"},
	{"Backpack10"},
	{"Backpack11"},
	{"Backpack12"},
	{"Backpack13"},
	{"Backpack14"},
	{"Backpack15"},
	{"Backpack16"},
	{"Backpack17"},
	{"Backpack18"},
	{"Backpack19"},
	{"Backpack20"},
	{"Backpack21"},
	{"Backpack22"},
	{"Backpack23"},
	{"Backpack24"},
	{"Head"},
	{"Neck"},
	{"Body"},
	{"Rear"},
	{"LeftFinger"},
	{"RightFinger"},
	{"Hands"},
	{"Gridle"},
	{"Legs"},
};
BSDATAF(weari)