#include "main.h"

BSDATA(bonusi) = {
	{"Injury1", Injury, 1},
	{"Injury2", Injury, 2},
	{"Injury3", Injury, 3},
	{"InjuryM1", Injury, -1},
	{"InjuryM2", Injury, -2},
	{"SufferInjury1", Injury, 1, 1},
	{"SufferInjury2", Injury, 2, 1},
	{"SufferInjury3", Injury, 3, 1},
	{"SufferInjuryM1", Injury, -1, 1},
	{"Depletion1", Depletion, 1},
	{"Depletion2", Depletion, 2},
	{"Depletion3", Depletion, 3},
	{"Exhaustion1", Exhaustion, 1},
	{"Exhaustion2", Exhaustion, 2},
	{"Exhaustion3", Exhaustion, 3},
	{"SufferExhaustion1", Exhaustion, 1, 1},
	{"SufferExhaustion2", Exhaustion, 2, 1},
	{"SufferExhaustion3", Exhaustion, 3, 1},
	{"ExhaustionM1", Exhaustion, -1},
	{"ExhaustionM2", Exhaustion, -2},
	{"Wear1", Wear, 1},
	{"Wear2", Wear, 1},
	{"Wear3", Wear, 1},
	{"Morale1", Morale, 1},
	{"Morale2", Morale, 2},
	{"Morale3", Morale, 3},
};
BSDATAF(bonusi)