#include "main.h"

BSDATA(bonusi) = {
	{"Injury1", Injury, 1},
	{"Injury2", Injury, 2},
	{"Injury3", Injury, 3},
	{"InjuryM1", Injury, -1},
	{"InjuryM2", Injury, -2},
	{"SufferInjury1", Injury, 1, 1},
	{"SufferInjury2", Injury, 2, 1},
	{"SufferInjury3", Injury, 3, 1},
	{"SufferInjuryM1", Injury, -1, 1},
	{"Depletion1", Depletion, 1},
	{"Depletion2", Depletion, 2},
	{"Depletion3", Depletion, 3},
	{"Exhaustion1", Exhaustion, 1},
	{"Exhaustion2", Exhaustion, 2},
	{"Exhaustion3", Exhaustion, 3},
	{"SufferExhaustion1", Exhaustion, 1, 1},
	{"SufferExhaustion2", Exhaustion, 2, 1},
	{"SufferExhaustion3", Exhaustion, 3, 1},
	{"ExhaustionM1", Exhaustion, -1},
	{"ExhaustionM2", Exhaustion, -2},
	{"Wear1", Wear, 1},
	{"Wear2", Wear, 1},
	{"Wear3", Wear, 1},
	{"Morale1", Morale, 1},
	{"Morale2", Morale, 2},
	{"Morale3", Morale, 3},
	{"Harm1", Harm, 1},
	{"Harm2", Harm, 2},
	{"Harm3", Harm, 3},
	{"HarmM1", Harm, -1},
	{"SufferHarm1", Harm, 1, 1},
	{"SufferHarm2", Harm, 2, 1},
	{"SufferHarm3", Harm, 3, 1},
	{"SufferHarmM1", Harm, -1, 1},
	{"RangeP", Range, 1},
	{"RangeM", Range, -1},
	{"Choose1", Choose, 1},
	{"Choose2", Choose, 2},
	{"Choose3", Choose, 3},
	{"NoInflict", Ignore, 0, 0},
	{"NoSuffer", Ignore, 0, 1},
};
BSDATAF(bonusi)