#include "main.h"

BSDATA(techi) {
	{"PlasmaScoring", Red, {}},
	{"MagenDefenseGrid", Red, {1}},
	{"DuraniumArmor", Red, {2}},
	{"AssaultCannon", Red, {3}},
	{"NeuralMotivator", Green, {}},
	{"DacxiveAnimators", Green, {0, 1}},
	{"HyperMetabolism", Green, {0, 2}},
	{"X89BacterialWeapon", Green, {0, 3}},
	{"AntimassDeflectors", Blue, {}},
	{"GravityDriver", Blue, {0, 0, 1}},
	{"FleetLogistics", Blue, {0, 0, 2}},
	{"LightWaveDeflector", Blue, {0, 0, 3}},
	{"SarweenTools", Yellow, {}},
	{"GravitonLaserSystem", Yellow, {0, 0, 0, 1}},
	{"TransitDiodes", Yellow, {0, 0, 0, 2}},
	{"IntegratedEconomy", Yellow, {0, 0, 0, 3}},
	{"CruiserII", NoTech, {1, 1, 0, 1}},
	{"DreadnoughtII", NoTech, {0, 0, 2, 1}},
	{"DestroyerII", NoTech, {2}},
	{"PDSII", NoTech, {1, 0, 0, 1}},
	{"CarrierII", NoTech, {0,0,2}},
	{"FighterII", NoTech, {0, 1, 1}},
	{"InfantryII", NoTech, {0, 2}},
	{"SpaceDockII", NoTech, {0, 0, 0, 2}},
	{"WarSunTech", NoTech, {3, 0, 0, 1}},
};
assert_enum(techi, WarSunTech)