#include "bsdata.h"
#include "tag.h"

BSDATA(tagi) = {
	{"Arrows"},
	{"CharismaMinus"},
	{"Clumsy"},
	{"Dangerous"},
	{"Forceful"},
	{"IgnoreArmor"},
	{"Messy"},
	{"NeedArrows"},
	{"Precise"},
	{"Ration"},
	{"Reload"},
	{"Slow"},
	{"Stun"},
	{"Thrown"},
	{"TwoHanded"},
	{"Coins"},
	{"Injured"},
	{"Shaken"},
	{"Sick"},
	{"Muddled"},
	{"Tired"},
	{"Stressed"},
	{"DivineShock"},
	{"HealDebility"},
	{"HealPoison"},
	{"UsableGear"},
	{"Advantage"},
	{"Disadvantage"},
	{"Hand"},
	{"Close"},
	{"Reach"},
	{"Near"},
	{"Far"},
};
assert_enum(tagi, Far)