#include "code_package.h"

using namespace code;

BSDATA(operationi) = {
	{"OpNone"},
	{"UnaryNop"},
	{"BinaryPlus"},
	{"BinaryMinus"},
	{"BinaryDiv"},
	{"BinaryMul"},
	{"BinaryDivRest"},
	{"BinaryOr"},
	{"BinaryAnd"},
	{"BinaryXor"},
	{"UnaryNot"},
	{"UnaryNeg"},
	{"ShiftLeft"},
	{"ShiftRight"},
	{"ConditionLess"},
	{"ConditionLessEqual"},
	{"ConditionGreater"},
	{"ConditionGreaterEqual"},
	{"ConditionEqual"},
	{"ConditionNotEqual"},
	{"ConditionOr"},
	{"ConditionAnd"},
	{"BooleanChoose"},
	{"LeftIfTrue"},
	{"Increment"},
	{"Decrement"},
	{"UnaryAddressOf"},
	{"UnaryDereference"},
	{"BinaryScope"},
	{"Assign"},
	{"If"},
	{"While"},
	{"Return"},
	{"Switch"},
	{"Case"},
	{"Break"},
	{"Default"},
	{"Number"},
	{"Text"},
	{"Identifier"},
	{"Statement"},
};
assert_enum(operationi, operation::Statement)